apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: fecamp-2021-frontend
  namespace: master
  labels:
    app: fecamp-2021-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fecamp-2021-frontend
  template:
    metadata:
      labels:
        app: fecamp-2021-frontend
    spec:
      containers:
        - name: fecamp-2021-frontend
          image: ghcr.io/fecamp-cu/fe-2021-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
